### ISSUE TITLE
python highlight

### ISSUE THREAD

**Issue by econwang** [charls-data/Language-Stata#1]

**Comment by xyangwu** [comment]
Added highlight grammar in [Commit 1bb89f5](https://github.com/charls-data/Language-Stata/commit/1bb89f5e397b44cf62482f58e437740532010411) for Python code block:
- control keyword
- constant
- operator
- data type
- quotes
- comment

**Comment by xyangwu** [comment]
Update patterns of
- `python end` keyword
- string key. e.g. `df['key']`
- variable in f-string. e.g. `f'hello {name}'`

[Commit 44eef95](https://github.com/charls-data/Language-Stata/commit/1bb89f5e397b44cf62482f58e437740532010411)
