### ISSUE TITLE
frame highlight

### ISSUE THREAD

**Issue by econwang** [charls-data/Language-Stata#2]

**Comment by xyangwu** [comment]
Added highlight grammar in [Commit 1bb89f5](https://github.com/charls-data/Language-Stata/commit/1bb89f5e397b44cf62482f58e437740532010411) for command `frame` and `frlink`, `fralias`.
![highlight preview](https://github.com/user-attachments/assets/6da0f8bb-858a-436f-bb9e-98821677195c)
